In [3]:
import gym
from rich import print

## list all the atari gym environments
env_names = [env_spec.id for env_spec in gym.envs.registry.all()]
# print( env_names )
## print all the envs name with atari

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from stable_baselines3.common.buffers import ReplayBuffer
model = nn.Sequential(
    nn.Linear( 5 , 5),
    nn.ReLU(),
    nn.Linear( 5 , 10 ))
from rich import print
print( model )

/home/null/miniconda3/envs/cleanrl/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/null/miniconda3/envs/cleanrl/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py:5: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  tensorboard.__version__


Sequential(
  (0): Linear(in_features=5, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=10, bias=True)
)

In [5]:
print( model[0])
print( model[0].weight.data)
print( model[0].bias.data)

Linear(in_features=5, out_features=5, bias=True)

tensor([[-2.0911e-01, -4.4193e-01, -1.9880e-01, -1.4006e-01,  1.1163e-02],
        [-4.3219e-01,  1.8718e-04, -2.8189e-01, -6.3825e-02, -4.2294e-01],
        [ 3.2263e-01,  1.8390e-01,  2.4258e-01, -1.5691e-02, -1.0865e-01],
        [-1.9293e-01, -2.6274e-01, -2.7591e-01,  1.6678e-01,  2.8082e-01],
        [ 1.4296e-02,  3.6439e-01,  3.3404e-01,  3.0173e-01,  3.3472e-01]])

tensor([-0.0282,  0.2211, -0.0189, -0.4369, -0.0341])

In [6]:
import torch

print( getattr( torch ,  "quint8"))
print( getattr( torch.ao.quantization ,  "MovingAverageMinMaxObserver"))

torch.quint8

<class 'torch.ao.quantization.observer.MovingAverageMinMaxObserver'>

In [7]:
model = nn.Sequential(
    torch.ao.quantization.QuantStub(),
    nn.Linear( 5 , 5),
    nn.ReLU(),
    nn.Linear( 5 , 10 ), 
    torch.ao.quantization.DeQuantStub())
print( model)

model.qconfig = torch.ao.quantization.get_default_qat_qconfig("fbgemm")

torch.ao.quantization.prepare_qat(model , inplace = True   )

print( model )
    

Sequential(
  (0): QuantStub()
  (1): Linear(in_features=5, out_features=5, bias=True)
  (2): ReLU()
  (3): Linear(in_features=5, out_features=10, bias=True)
  (4): DeQuantStub()
)

/home/null/miniconda3/envs/cleanrl/lib/python3.7/site-packages/torch/ao/quantization/observer.py:216: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  reduce_range will be deprecated in a future release of PyTorch."


Sequential(
  (0): QuantStub(
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([1.]), zero_point=tensor([0], 
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
    )
  )
  (1): Linear(
    in_features=5, out_features=5, bias=True
    (weight_fake_quant): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([1.]), zero_point=tensor([0], 
dtype=torch.int32), dtype=torch.qint8, quant_min=-128, quant_max=127, qscheme=torch.per_channel_symmetric, 
reduce_range=False
      (activation_post_process): MovingAveragePerChannelMinMaxObserver(min_val=tensor([]), max_val=tensor([]))
    )
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([1.]), zero_point=tensor([0], 
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
    )
  )
  (2): ReLU()
  (3): Linear(
    in_features=5, out_features=10, bias=True
    (weight_fake_quant): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([1.]), zero_point=tensor([0], 
dtype=torch.int32), dtype=torch.qint8, quant_min=-128, quant_max=127, qscheme=torch.per_channel_symmetric, 
reduce_range=False
      (activation_post_process): MovingAveragePerChannelMinMaxObserver(min_val=tensor([]), max_val=tensor([]))
    )
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([1.]), zero_point=tensor([0], 
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
    )
  )
  (4): DeQuantStub()
)

In [8]:
x = torch.randn([1, 1, 5])
print(  x ) 
print( model(x))
print( model)

tensor([[[-0.8817, -0.4927, -0.1196,  0.2639, -0.5099]]])

tensor([[[-0.0502,  0.1407, -0.0804,  0.3467, -0.0100,  0.3065, -0.1206,
          -0.2914, -0.0553,  0.2612]]],
       grad_fn=<FusedMovingAvgObsFqHelperBackward0>)

Sequential(
  (0): QuantStub(
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0090]), zero_point=tensor([98],
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=-0.8817196488380432, 
max_val=0.26394128799438477)
    )
  )
  (1): Linear(
    in_features=5, out_features=5, bias=True
    (weight_fake_quant): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0027, 0.0016, 0.0035, 0.0027, 
0.0028]), zero_point=tensor([0, 0, 0, 0, 0], dtype=torch.int32), dtype=torch.qint8, quant_min=-128, quant_max=127, 
qscheme=torch.per_channel_symmetric, reduce_range=False
      (activation_post_process): MovingAveragePerChannelMinMaxObserver(min_val=tensor([-0.2244, -0.0561, -0.4467, 
-0.3462, -0.3555]), max_val=tensor([0.3482, 0.2076, 0.4098, 0.2362, 0.1118]))
    )
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0052]), zero_point=tensor([69],
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=-0.3596686124801636, 
max_val=0.30444252490997314)
    )
  )
  (2): ReLU()
  (3): Linear(
    in_features=5, out_features=10, bias=True
    (weight_fake_quant): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0031, 0.0033, 0.0030, 0.0019, 
0.0030, 0.0026, 0.0032, 0.0033, 0.0034,
              0.0019]), zero_point=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32), dtype=torch.qint8, 
quant_min=-128, quant_max=127, qscheme=torch.per_channel_symmetric, reduce_range=False
      (activation_post_process): MovingAveragePerChannelMinMaxObserver(
        min_val=tensor([-0.0068, -0.4262, -0.3818, -0.2456, -0.1737, -0.3336, -0.4121, -0.4166,
                -0.3722, -0.2402]), max_val=tensor([0.3994, 0.3824, 0.2180, 0.2366, 0.3865, 0.1615, 0.2880, 0.2146,
0.4348,
                0.1583])
      )
    )
    (activation_post_process): FusedMovingAvgObsFakeQuantize(
      fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0050]), zero_point=tensor([58],
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
      (activation_post_process): MovingAverageMinMaxObserver(min_val=-0.29220107197761536, 
max_val=0.3458470106124878)
    )
  )
  (4): DeQuantStub()
)

In [9]:
print( model[0])

QuantStub(
  (activation_post_process): FusedMovingAvgObsFakeQuantize(
    fake_quant_enabled=tensor([1]), observer_enabled=tensor([1]), scale=tensor([0.0090]), zero_point=tensor([98], 
dtype=torch.int32), dtype=torch.quint8, quant_min=0, quant_max=127, qscheme=torch.per_tensor_affine, 
reduce_range=True
    (activation_post_process): MovingAverageMinMaxObserver(min_val=-0.8817196488380432, 
max_val=0.26394128799438477)
  )
)

In [10]:
y = model[0](x)
print( y.dtype)
y = model[1](y)
print( y.dtype)
y  = model[2](y)
print( y.dtype)

torch.float32

torch.float32

torch.float32

In [11]:
# Convert the prepare QA model to a quantized model
model_int8 = torch.ao.quantization.convert(model)

In [12]:
print( model_int8)

Sequential(
  (0): Quantize(scale=tensor([0.0090]), zero_point=tensor([98]), dtype=torch.quint8)
  (1): QuantizedLinear(in_features=5, out_features=5, scale=0.005229221656918526, zero_point=69, 
qscheme=torch.per_channel_affine)
  (2): ReLU()
  (3): QuantizedLinear(in_features=5, out_features=10, scale=0.005024000536650419, zero_point=58, 
qscheme=torch.per_channel_affine)
  (4): DeQuantize()
)